export const MANAGER_PERMISSION_MODULE = {
  MAIN: 'MAIN',
  WINFIT_ONLINE: 'WINFIT_ONLINE',
  MANAGEMENT_HOME_PAGE: 'MANAGEMENT_HOME_PAGE',
  MANAGEMENT_ABOUT_ME_PAGE: 'MANAGEMENT_ABOUT_ME_PAGE',
  ADMIN: 'ADMIN',
};
