name: "tt-library-angular-porfolio"

on:
  push:
    branches:
      - deploy

jobs:
  release:
    name: "tt-library-angular-porfolio"
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4.1.1

      - name: node
        uses: actions/setup-node@v4.0.2
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org

      - name: install
        run: npm i

      - name: update patch version
        run: cd projects/tt-library-angular-porfolio
             npm version patch

      - name: push new version
        run: cd ../../
             git config --global user.name 'thanhtung1010'
             git config --global user.email 'trinhthanhtung1010@gmail.com'
             git commit -m "update lib version"
             git push

      - name: build
        run: npm run build

      - name: publish
        run: npm publish ./dist/tt-library-angular-porfolio -access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
