name: "tt-library-angular-porfolio"

on:
  push:
    branches:
      - deploy

jobs:
  release:
    name: "tt-library-angular-porfolio"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
        with:
          ssh-key: ${{secrets.SSH_GIT_ACTION}}

      - name: Node
        uses: actions/setup-node@v4.0.2
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org

      - name: Install
        run: npm i

      - name: Update patch version
        run: cd projects/tt-library-angular-porfolio
             && npm version patch

      - name: Push new version
        run: git config --global user.name 'thanhtung1010'
             && git config --global user.email 'trinhthanhtung1010@gmail.com'
             && git add .
             && git commit -m "update lib version"
             && git push

      - name: Build
        run: npm run build

      - name: Publish
        run: npm publish ./dist/tt-library-angular-porfolio -access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
