name: "tt-library-angular-porfolio"

on:
  push:
    branches:
      - deploy

jobs:
  release:
    name: "tt-library-angular-porfolio"
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4.1.1

      - name: node
        uses: actions/setup-node@v4.0.2
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org

      - name: install
        run: npm i

      - name: build
        run: npm run build

      - name: go to dist
        run: cd dist

      - name: publish
        run: npm publish -access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
